// <auto-generated />
using System;
using ConfitecApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConfitecApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200928172523_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ConfitecApi.Model.Escolaridade", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Escolaridades");

                    b.HasData(
                        new
                        {
                            id = 1,
                            descricao = "Infantil"
                        },
                        new
                        {
                            id = 2,
                            descricao = "Fundamental"
                        },
                        new
                        {
                            id = 3,
                            descricao = "Médio"
                        },
                        new
                        {
                            id = 4,
                            descricao = "Superior"
                        });
                });

            modelBuilder.Entity("ConfitecApi.Model.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("escolaridadeId")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sobrenome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("escolaridadeId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            id = 1,
                            dataNascimento = new DateTime(1999, 7, 7, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "lsilva@gmail.com",
                            escolaridadeId = 1,
                            nome = "Lauro",
                            sobrenome = "Silva"
                        },
                        new
                        {
                            id = 2,
                            dataNascimento = new DateTime(1989, 9, 3, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "rsilva@gmail.com",
                            escolaridadeId = 2,
                            nome = "Roberto",
                            sobrenome = "Silva"
                        },
                        new
                        {
                            id = 3,
                            dataNascimento = new DateTime(1991, 10, 20, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "r.silva@gmail.com",
                            escolaridadeId = 3,
                            nome = "Ronaldo",
                            sobrenome = "Silva"
                        },
                        new
                        {
                            id = 4,
                            dataNascimento = new DateTime(1992, 12, 24, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "r_silva@gmail.com",
                            escolaridadeId = 1,
                            nome = "Rodrigo",
                            sobrenome = "Silva"
                        },
                        new
                        {
                            id = 5,
                            dataNascimento = new DateTime(1995, 7, 17, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            email = "lsilva@gmail.com",
                            escolaridadeId = 4,
                            nome = "Alexandre",
                            sobrenome = "Silva"
                        });
                });

            modelBuilder.Entity("ConfitecApi.Model.Usuario", b =>
                {
                    b.HasOne("ConfitecApi.Model.Escolaridade", "Escolaridade")
                        .WithMany()
                        .HasForeignKey("escolaridadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
